/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extension from "./extension";
export type { extension };
export type { IONFT1155 } from "./IONFT1155";
export type { IONFT1155Core } from "./IONFT1155Core";
export type { IONFT721 } from "./IONFT721";
export type { IONFT721Core } from "./IONFT721Core";
export type { ONFT1155 } from "./ONFT1155";
export type { ONFT1155Core } from "./ONFT1155Core";
export type { ONFT721 } from "./ONFT721";
export type { ONFT721Core } from "./ONFT721Core";
