/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IStabilityPoolManagerInterface extends utils.Interface {
  functions: {
    "addStabilityPool(address,address)": FunctionFragment;
    "getAssetStabilityPool(address)": FunctionFragment;
    "isStabilityPool(address)": FunctionFragment;
    "unsafeGetAssetStabilityPool(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addStabilityPool"
      | "getAssetStabilityPool"
      | "isStabilityPool"
      | "unsafeGetAssetStabilityPool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addStabilityPool",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetStabilityPool",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isStabilityPool",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unsafeGetAssetStabilityPool",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addStabilityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetStabilityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStabilityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsafeGetAssetStabilityPool",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IStabilityPoolManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStabilityPoolManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addStabilityPool(
      asset: PromiseOrValue<string>,
      stabilityPool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isStabilityPool(
      stabilityPool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    unsafeGetAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  addStabilityPool(
    asset: PromiseOrValue<string>,
    stabilityPool: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAssetStabilityPool(
    asset: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  isStabilityPool(
    stabilityPool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  unsafeGetAssetStabilityPool(
    asset: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    addStabilityPool(
      asset: PromiseOrValue<string>,
      stabilityPool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    isStabilityPool(
      stabilityPool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unsafeGetAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addStabilityPool(
      asset: PromiseOrValue<string>,
      stabilityPool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isStabilityPool(
      stabilityPool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unsafeGetAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addStabilityPool(
      asset: PromiseOrValue<string>,
      stabilityPool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isStabilityPool(
      stabilityPool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unsafeGetAssetStabilityPool(
      asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
