/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  TroveManagerScript,
  TroveManagerScriptInterface,
} from "../../../contracts/Proxy/TroveManagerScript";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ITroveManager",
        name: "_troveManager",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_AGLmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_firstRedemptionHint",
        type: "address",
      },
      {
        internalType: "address",
        name: "_upperPartialRedemptionHint",
        type: "address",
      },
      {
        internalType: "address",
        name: "_lowerPartialRedemptionHint",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_partialRedemptionHintNICR",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxIterations",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maxFee",
        type: "uint256",
      },
    ],
    name: "redeemCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b506040516102f43803806102f483398101604081905261002f916100f7565b61003881610049565b6001600160a01b0316608052610127565b6001600160a01b0381166100a45760405162461bcd60e51b815260206004820152601e60248201527f4163636f756e742063616e6e6f74206265207a65726f2061646472657373000060448201526064015b60405180910390fd5b803b806100f35760405162461bcd60e51b815260206004820181905260248201527f4163636f756e7420636f64652073697a652063616e6e6f74206265207a65726f604482015260640161009b565b5050565b60006020828403121561010957600080fd5b81516001600160a01b038116811461012057600080fd5b9392505050565b6080516101b561013f600039600050506101b56000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806340a44bd11461003b578063a3f4df7e14610055575b600080fd5b6100536100493660046100b8565b5050505050505050565b005b61008660405180604001604052806012815260200171151c9bdd9953585b9859d95c94d8dc9a5c1d60721b81525081565b6040516100939190610131565b60405180910390f35b80356001600160a01b03811681146100b357600080fd5b919050565b600080600080600080600080610100898b0312156100d557600080fd5b6100de8961009c565b9750602089013596506100f360408a0161009c565b955061010160608a0161009c565b945061010f60808a0161009c565b979a969950949793969560a0850135955060c08501359460e001359350915050565b600060208083528351808285015260005b8181101561015e57858101830151858201604001528201610142565b506000604082860101526040601f19601f830116850101925050509291505056fea264697066735822122024912ec2fbe0ab6192f6358330d0be1418206ad1c9a14d696bda6daa94927ede64736f6c63430008130033";

type TroveManagerScriptConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TroveManagerScriptConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TroveManagerScript__factory extends ContractFactory {
  constructor(...args: TroveManagerScriptConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _troveManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<TroveManagerScript> {
    return super.deploy(
      _troveManager,
      overrides || {}
    ) as Promise<TroveManagerScript>;
  }
  override getDeployTransaction(
    _troveManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_troveManager, overrides || {});
  }
  override attach(address: string): TroveManagerScript {
    return super.attach(address) as TroveManagerScript;
  }
  override connect(signer: Signer): TroveManagerScript__factory {
    return super.connect(signer) as TroveManagerScript__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TroveManagerScriptInterface {
    return new utils.Interface(_abi) as TroveManagerScriptInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TroveManagerScript {
    return new Contract(address, _abi, signerOrProvider) as TroveManagerScript;
  }
}
