/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGLPStaked,
  IGLPStakedInterface,
} from "../../../contracts/Interfaces/IGLPStaked";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGLPStaked__factory {
  static readonly abi = _abi;
  static createInterface(): IGLPStakedInterface {
    return new utils.Interface(_abi) as IGLPStakedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGLPStaked {
    return new Contract(address, _abi, signerOrProvider) as IGLPStaked;
  }
}
